import React from 'react';
import { HandoverSummary } from '../types';

interface DoctorHandoverProps {
  summary: HandoverSummary;
  onClose: () => void;
}

const DoctorHandover: React.FC<DoctorHandoverProps> = ({ summary, onClose }) => {
  return (
    <div className="fixed inset-0 z-[100] bg-background/60 backdrop-blur-xl flex items-end md:items-center justify-center p-0 md:p-8 animate-in fade-in duration-500">
      <div className="bg-surface w-full max-w-3xl h-[95vh] md:h-auto md:max-h-[90vh] rounded-t-[2.5rem] md:rounded-[3.5rem] shadow-2xl border border-border/60 overflow-hidden flex flex-col animate-in slide-in-from-bottom-full md:slide-in-from-bottom-12 duration-700">

        {/* Medical Header */}
        <div className="bg-primary p-7 md:p-10 text-white relative flex-shrink-0 overflow-hidden">
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-white/20 rounded-full blur-[80px] pointer-events-none"></div>
          <div className="absolute -bottom-24 -left-24 w-64 h-64 bg-accent/20 rounded-full blur-[80px] pointer-events-none"></div>
          <div className="flex justify-between items-start relative z-10">
            <div>
              <div className="flex items-center gap-2 md:gap-3 mb-2">
                <i className="fa-solid fa-clipboard-user text-xl md:text-2xl opacity-80"></i>
                <h2 className="text-lg md:text-2xl font-black uppercase tracking-tight">Clinical Handover</h2>
              </div>
              <p className="text-white/80 font-bold text-[10px] md:text-sm">
                Generated by Clinical Companion • {new Date().toLocaleDateString()}
              </p>
            </div>
            <button
              onClick={onClose}
              className="bg-black/10 hover:bg-black/20 p-2 md:p-3 rounded-xl md:rounded-2xl transition-all"
            >
              <i className="fa-solid fa-xmark text-lg md:text-xl"></i>
            </button>
          </div>

          <div className="mt-4 md:mt-6 flex gap-4 md:gap-8 relative z-10">
            <div>
              <span className="text-[9px] md:text-[10px] font-black uppercase opacity-60 block mb-0.5">Patient Name</span>
              <p className="text-base md:text-xl font-bold">{summary.patient_name}</p>
            </div>
            <div>
              <span className="text-[9px] md:text-[10px] font-black uppercase opacity-60 block mb-0.5">Status</span>
              <p className="text-base md:text-xl font-bold flex items-center gap-1.5 md:gap-2">
                <span className="w-2.5 h-2.5 bg-green-400 rounded-full animate-pulse shadow-[0_0_8px_rgba(74,222,128,0.6)]"></span>
                Ready
              </p>
            </div>
          </div>
        </div>

        {/* Clinical Content */}
        <div className="flex-1 overflow-y-auto p-5 md:p-8 space-y-6 md:space-y-8 bg-surface">

          {/* Narrative Summary */}
          <section className="bg-black/5 dark:bg-white/5 rounded-2xl md:rounded-3xl p-5 md:p-6 border border-border shadow-inner">
            <h3 className="text-[10px] font-black text-primary uppercase tracking-widest mb-3 flex items-center gap-2">
              <i className="fa-solid fa-comment-medical"></i>
              Summary
            </h3>
            <p className="text-text-primary leading-relaxed font-medium italic text-base md:text-lg">
              "{summary.narrative_summary}"
            </p>
          </section>

          {/* New Consultations Section */}
          {summary.recent_consultations && summary.recent_consultations.length > 0 && (
            <section className="space-y-3">
              <h3 className="text-[10px] md:text-[11px] font-black text-primary uppercase tracking-widest flex items-center gap-2">
                <i className="fa-solid fa-user-doctor"></i>
                Recent Professional Consultations
              </h3>
              <div className="bg-primary/5 p-4 rounded-2xl border border-primary/20 space-y-2">
                {summary.recent_consultations.map((consult, i) => (
                  <p key={i} className="text-xs md:text-sm text-primary font-bold">
                    • {consult}
                  </p>
                ))}
              </div>
            </section>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">

            {/* Chief Complaints */}
            <section className="space-y-3">
              <h3 className="text-[10px] md:text-[11px] font-black text-text-secondary uppercase tracking-widest flex items-center gap-2">
                <i className="fa-solid fa-head-side-virus text-danger"></i>
                Symptoms
              </h3>
              <div className="space-y-2">
                {summary.chief_complaints.map((item, i) => (
                  <div key={i} className="bg-background px-4 py-2.5 rounded-xl md:rounded-2xl border border-border shadow-sm flex items-center gap-3">
                    <div className="w-1.5 h-1.5 rounded-full bg-danger"></div>
                    <span className="text-text-primary font-bold text-sm md:text-base">{item}</span>
                  </div>
                ))}
              </div>
            </section>

            {/* Pre-Hospital Meds */}
            <section className="space-y-3">
              <h3 className="text-[10px] md:text-[11px] font-black text-text-secondary uppercase tracking-widest flex items-center gap-2">
                <i className="fa-solid fa-pills text-primary"></i>
                Medications
              </h3>
              <div className="space-y-2">
                {summary.medications_pre_hospital.map((item, i) => (
                  <div key={i} className="bg-background px-4 py-2.5 rounded-xl md:rounded-2xl border border-border shadow-sm flex items-center gap-3">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary"></div>
                    <span className="text-text-primary font-bold text-sm md:text-base">{item}</span>
                  </div>
                ))}
              </div>
            </section>

          </div>

          {/* Observations & Flags */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">

            <section className="space-y-3">
              <h3 className="text-[10px] md:text-[11px] font-black text-text-secondary uppercase tracking-widest flex items-center gap-2">
                <i className="fa-solid fa-eye text-success"></i>
                Observations
              </h3>
              <div className="bg-success/5 p-4 md:p-5 rounded-2xl md:rounded-3xl border border-success/20 space-y-2 md:space-y-3">
                {summary.recent_observations.map((item, i) => (
                  <p key={i} className="text-xs md:text-sm text-text-primary font-medium">
                    • {item}
                  </p>
                ))}
              </div>
            </section>

            <section className="space-y-3">
              <h3 className="text-[10px] md:text-[11px] font-black text-text-secondary uppercase tracking-widest flex items-center gap-2">
                <i className="fa-solid fa-triangle-exclamation text-warning"></i>
                Flags
              </h3>
              <div className="bg-warning/5 p-4 md:p-5 rounded-2xl md:rounded-3xl border border-warning/20 space-y-2 md:space-y-3">
                {summary.clinical_flags.length > 0 ? summary.clinical_flags.map((item, i) => (
                  <p key={i} className="text-sm text-warning font-bold">
                    ⚠️ {item}
                  </p>
                )) : (
                  <p className="text-xs md:text-sm text-text-secondary/70 italic">No critical flags detected.</p>
                )}
              </div>
            </section>

          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-5 md:p-8 border-t border-border bg-surface flex flex-col md:flex-row gap-4 justify-between items-center flex-shrink-0">
          <div className="hidden md:flex items-center gap-4 text-xs text-text-secondary/70 font-bold uppercase tracking-widest">
            <i className="fa-solid fa-fingerprint text-primary/50"></i>
            Audit: HAND-{Math.floor(Math.random() * 100000)}
          </div>
          <div className="flex w-full md:w-auto gap-3">
            <button
              onClick={() => window.print()}
              className="flex-1 md:flex-none px-4 md:px-6 py-3 rounded-xl md:rounded-2xl text-xs md:text-sm font-bold border border-border text-text-primary hover:bg-black/5 dark:hover:bg-white/5 transition-all flex items-center justify-center gap-2 shadow-sm"
            >
              <i className="fa-solid fa-print text-text-secondary"></i>
              Print
            </button>
            <button
              onClick={onClose}
              className="bg-text-primary text-background dark:text-background px-6 md:px-8 py-3 rounded-xl md:rounded-2xl text-xs md:text-sm font-bold shadow-md hover:scale-[1.02] active:scale-[0.98] transition-all"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default DoctorHandover;
